### ISSUE TITLE
Training script issue

### ISSUE THREAD

**Issue by ARVRTest** [google/shuwa#2]
Hi, thank you for sharing this code!

We would like to ask for help about the error that we encounter while running the training script on our data with 10 words only.
In the jupyter notebook, the model.fit_generator() produces the following error:

InvalidArgumentError:  Input to reshape is a tensor with 10 values, but the requested shape has 1
	 [[node Reshape
 (defined at /Users/abc/opt/anaconda3/envs/githubshuwa/lib/python3.7/site-packages/tensorflow_addons/losses/triplet.py:257)
]] [Op:__inference_train_function_13545]

We used the following tool versions:
1. Python 3.7
2. Tensorflow 2.6

And we also updated the batch from 32 to 1 because the demo webapp expects the model to have an input shape with 1 batch only.

We would like to ask:
1. What versions of python and Tensorflow should we use?
2. Are there other possible cause for the error that we encountered?
3. How can we train using more than 1 batch without affecting the expected shape of the input of the model?

Thank you very much in advance!

**Comment by bit-dome** [comment]
1. We used Tensorflow2.4 

2. This error could be caused by a mismatch in the shape of the labels in the triplet loss function. 
          the function accepts two inputs in this sequence
         - y_true 1D<integer> Labels:     the shape should be [batch_size] (not one-hot encoding)
         - y_pred 2D<float> Model output:     the shape should be [batch_size, num_l2_feats].

3. You cannot train using using batch_size of 1, Because of the way the online triplet loss works.
	- Train with a batch size of 32, 64,128, 256 or any other size that fits your hardware.
	- Save the weight after the model has been trained. 
	- Restart Jupyter notebook and create a model with input batch_size of 1
	- Load the weight back in to the model.
	- Convert to TFJS model

**Comment by ARVRTest** [comment]
Hi thank you very much for your prompt response.

We tried to train again using Tensorflow 2.4/Python 3.7 but we still encountered the reshape error.
Checking the documentation of Keras Sequence, we updated the keras Sequence data generator to output only the y_true 1D labels, and the training script ran successfully. Please see code modification below:

File: shuwa-main/classifier/dd_data_generator.py (returned y_batch only instead of  [y_batch, cls_batch])

` def __getitem__(self, item):
       ...
       return [pose_frames_batch, face_frames_batch, left_hand_frames_batch, right_hand_frames_batch],  y_batch` 

   
Is the modification above OK? We are not sure if this is the right way to solve the issue but we were able to use the output weights for the next steps.

We were able to train with batch size 32 and resize the weights to batch_size 1 as instructed.

Thanks again for your support. This is a very good material.

**Comment by bit-dome** [comment]
It seems that the "cls_output" node was created for the previous web version, and we missed to remove it from the Python code.
Thank you for your advice. 
https://github.com/google/shuwa/commit/3fbc72bf9d189eeb727797d8367292023c3f1dbd
